### ISSUE TITLE
Refresh reroutes development server to index

### ISSUE THREAD

**Issue by davidrhoderick** [frontity/frontity#124]
This is a small issue but it would be more sensible if on saving files that have been changed, the current route is maintained and the site doesn't refresh to the index route.  I would expect it to work that way but it doesn't.

**Comment by luisherranz** [comment]
Hey David, thanks for the report.

You're absolutely right. That happens because HMR (hot module replacement) is not working yet on our state manager (Frontity Connect) and `state.router.link` is reseted to `"/"` when HMR is triggered.

Adding HMR to Connect is on our 1.0 roadmap: https://community.frontity.org/t/1-0-roadmap-progress/207. It's not difficult to do, it's just that we haven't had time to do it yet :)

I'll close this issue once it's done.

**Comment by davidrhoderick** [comment]
Hey @luisherranz, thanks for adding this to the roadmap.

I'm not sure if you want to add as well automatic opening of the front-end in the default browser when the server spins up (not sure if it constitutes a separate issue nor if you are interested in that behavior).  Usually when I use automation serve my projects, I have it open a new window/tab in my default browser.  No problem if it's not your preference to have that behavior.

**Comment by luisherranz** [comment]
Thanks for the suggestion. I've just made a PR with that feature: https://github.com/frontity/frontity/pull/126 :)
