### ISSUE TITLE
Create a super-accessible starter theme using reakit

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#158]
[Reakit](https://reakit.io/) looks like a super nice way to create accessible sites.

We could add a starter theme, similar to mars, but using Reakit underneath to support [WAI-ARIA 1.1](https://www.w3.org/TR/wai-aria/).

**Comment by sagarnasit** [comment]
@luisherranz Let's dig into this.

**Comment by luisherranz** [comment]
Sure. Have you checked their documentation?
https://reakit.io/docs/get-started/

I shouldn't be very difficult to do. Maybe the menu could use their menu components and VisuallyHidden could be use to skip to the content.

I'm not an expert on accessibility myself so maybe there's much more that can be done.

**Comment by luisherranz** [comment]
Maybe pagination could use their buttons as well: https://mars.frontity.org/

**Comment by diegohaz** [comment]
Hey 👋

To be honest, by looking at https://mars.frontity.org/, I don't see much that Reakit could help right now since it's currently mostly focused on interactive widgets, and your theme doesn't seem to include them.

For now, you should focus on landmark roles, such as [main](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Main_role), [banner](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Banner_role) and a [few others](https://www.w3.org/WAI/GL/wiki/Using_ARIA_landmarks_to_identify_regions_of_a_page). There's also this [accessible Feed example](https://www.w3.org/TR/wai-aria-practices/examples/feed/feed.html) you may want to look at.

Most of those landmarks have equivalent HTML tags such as `<main>` and `<header>`. You should use them. This is the most important thing about web accessibility. People using screen readers don't use <kbd>Tab</kbd> as their primary way to navigate through a page. They use tools like the Voice Over Rotor, which looks like this:

![Visually demonstrating the Voice Over Rotor in the Landmarks mode](https://cdn-images-1.medium.com/max/1600/1*UvPYFq4GduXFlrTCJ4YLFw.jpeg)

For buttons, just use `<button>`, and you'll be fine. :)

We do have plans to provide structural components like `Main`, `Banner` and `Feed` on Reakit, but it's not the highest priority right now as these are easier to tackle (although information about them still needs to be spread).

**Comment by luisherranz** [comment]
Thanks for chiming in @diegohaz ☺️ 

We'll look into the landmark roles.

So, a part from that, most of it would be about adding a menu with dropdown submenus navigable using the keyboard and maybe VisallyHiden (Skip to main content) componet. Is that right?

**Comment by diegohaz** [comment]
So, will you have a dropdown menu? If so, yes, Reakit can definitely help with that. I haven't seen anything like that on https://mars.frontity.org/, thus didn't suggested it.

I don't recommend `VisuallyHidden` for "Skip to main content" as this might be useful for sighted users using keyboard only. For https://reakit.io, I created [this component](https://github.com/reakit/reakit/blob/9fcd5bcd98226d1b2dad397f80887b90fb88a047/packages/website/src/components/SkipToContent.ts). It uses internal stuff from reakit and website, but the CSS part might be useful for you.

You can also open a feature request for a built-in `SkipToMainContent` component on Reakit. It will be probably useful for more people.

**Comment by luisherranz** [comment]
Sorry for the delay here.

> So, will you have a dropdown menu? If so, yes, Reakit can definitely help with that.

Thanks @diegohaz, that's great :)

> For https://reakit.io, I created this component. It uses internal stuff from reakit and website, but the CSS part might be useful for you.

That's great as well!

> You can also open a feature request for a built-in SkipToMainContent component on Reakit. It will be probably useful for more people.

Good idea, although I'm not sure if I'm the right person as I'm still quite newbie in terms of accessibility 😅

**Comment by luisherranz** [comment]
Close as this should be added as a Feature Discussion in our Community forum.
