### ISSUE TITLE
Array elements from package state are duplicated on `csr`

### ISSUE THREAD

**Issue by orballo** [frontity/frontity#237]
**_Bug report_**

- [X] I've searched for existing issues
- [X] I've checked documentation: https://docs.frontity.org
- [ ] I've checked community forum: https://community.frontity.org

**Describe the expected behavior**

When I define an array inside a theme `index.js` file like this:
```js
const theme = {
  name: "noticias-coches-theme",
  roots: {
    theme: Root
  },
  state: {
    theme: {
      nav: [ { label: "One", link: "/one" }, { label: "Two", link: "/two" } ]
    }
  }
};
```

The menu should be rendered once, as if defined in `frontity.settings.js`.

**Describe the observed behavior**

Instead the menu is rendered once in `ssr` and duplicated in every `csr`.

**Comment by DAreRodz** [comment]
I've done some research and the problem is happening when calling [mergePackages](https://github.com/frontity/frontity/blob/f6de112114132f1758ee4a12ad09860e247372d3/packages/core/src/client/store.ts#L15) during Client Side Rendering (more specifically in [this line](https://github.com/frontity/frontity/blob/f6de112114132f1758ee4a12ad09860e247372d3/packages/core/src/utils/merge-packages.ts#L33L35)).

**Comment by luisherranz** [comment]
`deepmerge` accepts an `arrayMerge`. The problem is that is we go back to overwrite, you cannot add elements to arrays in the state declaration because the next array will delete the first ones.

**Comment by luisherranz** [comment]
Let me think about it...

**Comment by luisherranz** [comment]
Ok, I guess we can try to do an overwrite at that point because the merge of the arrays already happened on the server and we are only hydrating the state.
