### ISSUE TITLE
Yarn isn't working [8pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#364]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**
Users expect to be able to use `yarn` instead of `npm`.

**Observed behavior**
`yarn` is not working because it doesn’t install local dependencies using `symlinks`. It copies the folder instead.

**Possible solution**
We can use `symlink-dir` at `frontity dev`.

**Comment by luisherranz** [comment]
More information in: https://community.frontity.org/t/support-for-yarn/861

**Comment by luisherranz** [comment]
The first thing we need to know is how to detect local packages:
https://docs.npmjs.com/configuring-npm/package-json.html#local-paths

Then, in `npx frontity dev` we should:
- Read the project's `package.json`.
- Extract local dependencies from the `dependencies` object.
- Apply [`symlink-dir`](https://www.npmjs.com/package/symlink-dir) to those folders.

```js
symlinkDir('./packages/mars-theme', './node_modules/@frontity/mars-theme')
```
The logic can be inserted at this point: https://github.com/frontity/frontity/blob/dev/packages/core/src/scripts/dev.ts#L32

To enter debug mode, run `npm run dev:inspect` in `examples/mars-theme` and set a breakpoint in `packages/core/dist/src/scripts/dev.js`. You may need to run `npm run dev:inspect` over and over to test this out because this point only gets executed once per `npx frontity dev`, not each time you refresh the page.

We don't have local dependencies on the `examples` projects. Create them manually and check also manually if the symlinks are being created.

To rebuild `core` automatically after each change, go to `packages/core` and run `npm run build:watch`.

**Comment by michalczaplinski** [comment]
I haven't done extensive research, below is a summary of the conversation that I had with @iamuchejude today and some findings:

1. The yarn team explicitly warns against using "aliases" and they recommend the `link:` protocol https://yarnpkg.com/features/protocols#why-is-the-link-protocol-recommended-over-aliases-for-path-mapping

2. They also support the `link:` and `patch:` protocols, which might or might not be what we are looking for.

**Comment by luisherranz** [comment]
Oh, great discover @michalczaplinski.

> The yarn team explicitly warns against using "aliases"

We are not using aliases.

> They also support the link: and patch: protocols, which might or might not be what we are looking for.

No, but they also have portals and the is the exact same implementation than npm has for files! So it looks like that the yarn team decided to break compatibility with npm on purpose and what npm does with `file:` they do with `portal:`.

That's really a shame because fixing this would be as simple as changing the `package.json`. But we can't use both, and therefore we can't support both.

Even though there are some options, like letting the user choose between npm or yarn on `npx frontity create`, they lead to problems in the future, when multiple people want to collaborate on the same project and they want to use different package managers.

We may use a `preinstall` script in the project and somehow check if the install command was called with yarn (I don't know if that is possible) and if it was, change the `package.json` to portals and then on a `postinstall` script change it back to files, but that would complicate things for people wanting to use their own `preinstall` and `postinstall` scripts.

Well, it's a shame that yarn has this functionality but with a different name. I don't see a way right now to take advantage of it, so my opinion is to fix the links ourselves with the approach @iamuchejude is doing right now.

**Comment by luisherranz** [comment]
Impressive work @iamuchejude. Congratulations!! 😄

**Comment by iamuchejude** [comment]
Thanks, @luisherranz 😃
