### ISSUE TITLE
Frontity doesn't work with Semantic UI [8pt]

### ISSUE THREAD

**Issue by luisherranz** [frontity/frontity#405]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

Frontity should work with Semantic UI.

**Observed behavior**

It returns an error:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'lodash/fp/compact' in '/home/mpaccione/Projects/mpaccione-react/packages/mars-theme/node_modules/semantic-ui-react/dist/es/lib'
```

More info at https://community.frontity.org/t/how-to-add-semantic-ui-to-a-frontity-projectx/1634

**Steps involved to reproduce the problem**

- Start a new project.
- Add the [Semantic UI React](https://www.npmjs.com/package/semantic-ui-react) library.

**Possible solution**

I think we may be breaking the dependency of `lodash/fp` because, in order to do tree shaking of lodash, we have an alias of `lodash` to `lodash-es` in Webpack: https://github.com/frontity/frontity/blob/dev/packages/core/src/config/webpack/resolve.ts#L14

My feeling is that `lodash-es` doesn't have `loadsh-es/fp` and therefore we are breaking the dependency. To solve it we should find a way to do tree shaking of `lodash/fp`, or avoid doing the alias for `lodash/fp`, or maybe the main library (`lodash`) now supports tree shaking and the alias is not needed anymore.

**Comment by SantosGuillamot** [comment]
I'm marking it as `priority: high` because, as far as I understood, `semantic-ui-react` seems the official library for Semantic UI in React so, as with any React library, it should work with Frontity right? Apart from that it seems like a pretty popular library and it has been mentioned in at least four discussions in the forum.

Just in case it helps: while trying to understand this a bit better I came up with [this article](https://www.azavea.com/blog/2019/03/07/lessons-on-tree-shaking-lodash/), which mentions:

>**If you are using Webpack v4, you don’t need to use lodash-es**. The lodash-es library supports tree-shaking out of the box because it uses ES modules. However, with lodash v4, tree-shaking works without additional configuration in Webpack v4. It is also worth noting is that if you use lodash-es and you have other dependencies that require lodash, both will end up in the app bundle.
