### ISSUE TITLE
Prompted even if `--no-prompt` option is set.

### ISSUE THREAD

**Issue by hexaltation** [frontity/frontity#538]
**_Bug report_**

Hello,
When passing the following command :

`$ npx frontity create --no-prompt --theme @frontity/mars-theme myapp`

or

`$ npx frontity create -n --theme @frontity/mars-theme myapp`

I'm prompted back

`? Do you want to receive framework updates by email? (y/N)`

**Expected behavior**

The cli should apply a default behaviour which must be set NO as answer to the question.

**Observed behavior**

A question is asked, while `--no-prompt` or `-n` option is set.

**Info about your system**

Reproduced on Ubuntu 20.04 and MacOS 10.15

**Possible solution**

Reading the code `packages/frontity/src/cli/create.ts` it seems that no default values are set for cli parameters if they are missing and -no-prompt is set.  
They are defined only if `promptUser` is True.  
Default values for name and theme should be defined as variables at top of the file, and not *hard-coded* in Question templates.
The value of `promptUser` must be evaluated before everything else and return with well set values if true.

I will try to submit a PR in the next days to fix it. It's possible that it will fix Issue #434 as well.

**Comment by michalczaplinski** [comment]
Hi @hexaltation 👋 !

Thanks for the bug report - you're right, this should not happen! I think you got a good grip on the problem so I just wanted to point out to 

1. The issue seems to be that we are prompting the user to subscribe to the newsletter regardless of whether `promptUser` is true or not here: https://github.com/frontity/frontity/blob/0636532b948a8a8aaaca2a25c9b89b5ea4891b97/packages/frontity/src/cli/create.ts#L94-L108 We should check the value of `promptUser` before we do that.

2. 
> It's possible that it will fix Issue #434 as well.

The #434 issue is related to the `create-package` command, not the `create` command but you're right, it's related conceptually 🙂 . If you wanna fix both, check out the latest comment in that issue: https://github.com/frontity/frontity/issues/434#issuecomment-675626215 for some more context.

**Comment by luisherranz** [comment]
Good trick @mburridge 👍

**Comment by luisherranz** [comment]
It will be fixed in https://github.com/frontity/frontity/pull/545.
