### ISSUE TITLE
`npx frontity serve` command takes too much time to start the server [8pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#605]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

I expect that, after running `npx frontity serve`, the Server starts in ~1sec at most.

**Observed behavior**

Right now, if we run it locally it can take ~10 seconds and even more (20-30) if we deploy it to serverless platforms like Google Cloud Run. This is not a big deal for local development or for a common server, but for serverless platforms, where the container is stopped and it has to start again from time to time, it really affects the performance.

**Steps involved to reproduce the problem**

Run `npx frontity serve` in any Frontity project. It should be instant and it isn't right now.

**Possible solution**

It seems this is caused by [`commander.js`](https://www.npmjs.com/package/commander), the library we're using for our CLI, so we could just not use commander for the `serve` command.

If we bypass commander and we run the serve script directly, the server takes much less to start. To test this, you just have to create a `server.js` file in the root of your project and run `node server.js` in the console instead of `npx frontity serve`. This way we can see the difference.

_server.js_:
```
const serve = require("@frontity/core/dist/src/scripts/serve").default;

serve({
  isHttps: false,
  port: 8080,
});
```
----
It seems that this is causing other problems as well, like the one explained in this [community topic](https://community.frontity.org/t/error-did-you-forget-to-run-frontity-build/1426/39?u=santosguillamot), and it is also solved bypassing commander.

**Comment by luisherranz** [comment]
I think we should do the same for `npx frontity build` because sometimes is going to run on a CI environment and it should be as fast as possible and consume as few resources as possible.

**Comment by luisherranz** [comment]
@cristianbote discovered that it was not `commander`, but `ts-node`. So we will have to look for another solution if we ever want to improve `npx frontity build`, probably using `tsc` to transpile `frontity.settings.ts` instead of using `ts-node`.

**Comment by luisherranz** [comment]
For reference, I tried transpiling the `frontity.settings.ts` file programatically to get rid of `ts-node` in the `npx frontity build` command as well using:

```js
const ts = require("typescript");
const file = ts.transpileModule(source, { compilerOptions });
```

but it doesn't make much sense because the `frontity.settings.ts` file will usually import other `.ts` files (https://github.com/frontity/frontity/blob/dev/examples/mars-theme-ts-example/frontity.settings.ts) so we need to properly transpile all of them.

The next approach could be to use `tsc` and save the transpiled files in a tmp folder, maybe something like `node_modules/.frontity/` but I'm not going to try until we see if using `ts-node` in `npx frontity build` represents a real problem or not.
