### ISSUE TITLE
Broken links in package READMEs

### ISSUE THREAD

**Issue by nb** [frontity/frontity#654]
In https://github.com/frontity/frontity/tree/dev/packages/frontity:

* More info on npx frontity create [here](https://docs.frontity.org/frontity-cli/create) – should probably lead to https://docs.frontity.org/frontity-cli/create-commands#create
* Have a look at the latest updates of this package in the [CHANGELOG](https://github.com/frontity/frontity/blob/dev/packages//CHANGELOG.md) – should probably be a relative one

Open Source Community section in many packages:
* Subscribe to our [newsletter](https://frontity.org/#newsletter) – the newsletter portion is below the fold for me, probably because of the twitter testimonials being lazy-loaded
* See our [Contributing](https://github.com/frontity/frontity/blob/dev/packages/contributing) section to find out how you can help develop Frontity, or improve this documentation.

**Comment by luisherranz** [comment]
Thanks for the heads up Nikolay! 🙂

---

@mburridge could you please take care of this? Take a look at all our READMEs, not only this one.

> Have a look at the latest updates of this package in the CHANGELOG – should probably be a relative one

I have just tried a relative link but it doesn't work because the README can be loaded from different URLs (like [1](https://github.com/frontity/frontity/blob/dev/packages/frontity), [2](https://github.com/frontity/frontity/blob/dev/packages/frontity/README.md), [3](https://www.npmjs.com/package/frontity)) so I guess we are forced to use absolute URLs for this one.

**Comment by nb** [comment]
> I have just tried a relative link but it doesn't work because the README can be loaded from different URLs

Based on their documentation and on my experience, [GitHub supports relative URLs.](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-readmes#relative-links-and-image-paths-in-readme-files)

**Comment by luisherranz** [comment]
Oh, I didn't know that. Thanks @nb.

@mburridge, I have published a new page, exclusively for the newsletter: https://frontity.org/newsletter/. Please use that link to avoid the problem Nikolay described.

**Comment by mburridge** [comment]
@luisherranz I've updated this file and also checked and updated the other README files. PR #655 is awaiting your review.

**Comment by luisherranz** [comment]
Thanks @mburridge.
