### ISSUE TITLE
Weird production-only behaviour of global styles with css vars

### ISSUE THREAD

**Issue by bjoluc** [frontity/frontity#753]
## Bug report

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

### Expected behavior

Using
```jsx
<Global styles={css(":root{--my-var:#000000}",  "#test{background-color: green;}")}/>
```
in [the theme's root component](https://github.com/bjoluc/frontity-weird-global-css-beaviour/blob/974cf73c00190d8a076122e6219f76d2e4b01063/packages/mars-theme/src/components/index.js#L7-L13) should render
```jsx
<div id="test" style={{ minHeight: "300px" }} />
```
green:
* During SSR and in the client
* In development and production builds

The css variable definition should not in any way affect the second css rule.
 
### Observed behavior

In development mode (`npm run dev`), everything works as expected. In production mode (`npm run build && npm run serve`), the box flashes green on page load (SSR works as expected) but quickly turns white on the first client-side render.

### Steps involved to reproduce the problem

* `npx frontity create`
* Modify the theme's root component as in [this example repo
](https://github.com/bjoluc/frontity-weird-global-css-beaviour/blob/main/packages/mars-theme/src/components/index.js)

#### System:
 - OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
 - CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
 - Memory: 8.77 GB / 15.56 GB
 - Shell: 5.0.17 - /bin/bash
#### Binaries:
 - Node: 14.16.0 - /usr/bin/node
 - npm: 7.6.3 - /usr/bin/npm
#### Browsers:
 - Chrome: Not Found
 - Firefox: 86.0
#### npmPackages:
 - @frontity/core: ^1.11.0 => 1.11.0 
 - @frontity/html2react: ^1.6.1 => 1.6.1 
 - @frontity/mars-theme: ./packages/mars-theme => 1.5.0 
 - @frontity/tiny-router: ^1.4.0 => 1.4.0 
 - @frontity/wp-source: ^1.11.2 => 1.11.2 
 - frontity: ^1.14.2 => 1.14.2 
#### npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found

### Possible solution
?

**Comment by cristianbote** [comment]
Hi @bjoluc,

Thanks for opening this issue! This issue looked weird indeed, so, I jumped on it to see what's happening here. The issue is with `@emotion/react`.

There's a missing `;` that's causing this.
https://github.com/bjoluc/frontity-weird-global-css-beaviour/blob/974cf73c00190d8a076122e6219f76d2e4b01063/packages/mars-theme/src/components/index.js#L9

To fix this, add it like so:
```jsx
const Theme = () => {
  return (
    <div>
      <Global
        styles={css(
          ":root{--my-var:#000000;}", // <-- here I've added the `;`
          "#test{background-color: green;}"
        )}
      />
      <div id="test" style={{ minHeight: "300px" }} />
    </div>
  );
};
```

Made two codesandbox and deployed them to Netlify to highlight the production env as well:
* Here's the one with the above fix
   * Codesandbox: https://codesandbox.io/s/emotion-css-global-css-bug-with-fix-1kicy?file=/src/index.js
   * Deployment: https://csb-1kicy.netlify.app/
* Here's the one with the bug
   * Codesandbox: https://codesandbox.io/s/emotion-css-global-css-bug-r4945?file=/src/index.js
   * Deployment: https://csb-r4945.netlify.app/

Haven't dug deeper than this, cause it's probably tied to how the css parser is working inside.

**Comment by bjoluc** [comment]
Thanks @cristianbote for the quick investigation! I didn't notice there was no semicolon at the end of the block. The breaking css variable rule was part of a minified css file of [Swiper](https://swiperjs.com/swiper-api#css-styles) which only provides minified css files for individual components, so there's no easy workaround for me here (except probably including the entire Swiper css bundle, which I would like to avoid performance-wise).
Removing the last semicolon in a css block seems to be common practice in css minification and still outputs valid css. Should I file an issue in `@emotion/react`? I decided against doing so initially because the issue is specific to CSR in production in Frontity and I do not know much about how Frontity configures emotion...

**Comment by cristianbote** [comment]
Glad I could help!

> Removing the last semicolon in a css block seems to be common practice in css minification and still outputs valid css.

Indeed, it is, for css properties and values.

>  Should I file an issue in `@emotion/react`

`emotion`, `styled-components` and others are using `stylis` to parse the strings into CSS. So I've verified if this is indeed coming from `stylis` and it seems so. You can interactively try it here https://stylis.js.org/. Also it seems it only happens when using CSS vars.

And if you think about it, it makes total sense, cause a css var can contain whitespace, newlines, etc. So a parser needs the `;` to make sure it reads the value entirely and correctly.

So, I believe it's the css minifier in this case who would need to adjust the removal of `;` if the last property defined is a css var.

**Comment by bjoluc** [comment]
Thanks a bunch for sharing your expertise; it is greatly appreciated! I discovered https://github.com/thysultan/stylis.js/issues/250 which deals with this exact issue. For now, I will likely regex myself around this on the minified styles. Thanks!
