### ISSUE TITLE
RangeError or RecursionError with page queries

### ISSUE THREAD

**Issue by danielbruni** [frontity/frontity#762]
**_Bug report_**

If i use multiple params/query on a page. The console throws an error.

**Expected behavior**
The page should load without error.

**Observed behavior**

Console throws ```Uncaught (in promise) RangeError: Maximum call stack size exceeded``` or ```Uncaught (in promise) InternalError: too much recursion``` and some components wont load.

**Steps involved to reproduce the problem**
Just add some query params to a frontity page url.
For example: https://frontity.org/?bla=bla&moep=moep&test=test

The Frontity.org page has the same problem.

**Comment by michalczaplinski** [comment]
Hi @danielbruni 👋 Thanks for the report!

I cannot reproduce this issue with the latest version of Frontity after creating a fresh project with `npx frontity create`. Neither does it show up when I use the official [Frontity Codesandbox](https://codesandbox.io/s/github/frontity/codesandbox-frontity).

But you're right that it happens in the frontity.org. The site is running one version of Frontity behind so I'm inclined to think that the issue is somehow related to this bug: https://github.com/frontity/frontity/issues/744.

Could you try to update to the latest Frontity version and check if the issue persists? 
(You can run `npx frontity info` in your project and paste the output to ensure you're on the latest version)

BTW: Curiously, this problem seems to only show up when you put three or more search params in the URL!

**Comment by danielbruni** [comment]
Hi @michalczaplinski  Thank you for the quick reply.

I updated all frontity packages and its working now as expected.

Thank you very much!
