### ISSUE TITLE
(yoast) %%page%% not interpreted in title field

### ISSUE THREAD

**Issue by codemonkeynorth** [frontity/frontity#845]
**_Bug report_**

`%%page%%` not interpreted in title field

**Expected behavior**

a title defined as such for a taxonomy:
`%%term_title%% Archives %%sep%% %%page%% %%sep%% %%sitename%%`

should give me eg
`General Archives - Page 2 of 3 - My Site`

**Observed behavior**

the title when i visit `/example_taxonomy/general/page/2/`

just shows `General Archives - My Site`

**Steps involved to reproduce the problem**

* install mars theme
* create a taxonomy (`example_taxonomy` in WP and assign 4 items with value "General")
* set params.per_page = 2 in frontity settings for the taxonomy
* visit `/example_taxonomy/general/page/2/`

this suggests frontity is not passing the page value correctly?

**Comment by codemonkeynorth** [comment]
actually I see this noted by @luisherranz  here : https://community.frontity.org/t/yoast-seo-rest-api-head-tags-compatibilty/1651/7

**Comment by luisherranz** [comment]
Yes, this is a current limitation of the Yoast plugin, because it doesn't expose the pagination in the REST API.

I have been pinging the Yoast time from time to time to see if they can finally add support for this but they haven't done so yet. We will update our `@frontity/yoast` package as soon as they do.

I'm going to close this issue for now, and I'll reopen it once they fix the problem.

Until then, if you really need this, I recommend you to overwrite the Yoast `<title>` of your archives with your own implementation. You can do so by creating a package that is included after `yoast`:

```js
// frontity.settings.js
export default {
  // ..
  packages: {
    // ..
    "@frontity/yoast",
    "archive-titles"
  }
}
```

```js
// packages/archive-titles/src/index.js
const ArchiveTitles = connect(({ state }) => {
  const data = state.source.get(state.router.link);
  if (data.isArchive) {
    return (
      <Head>
        <title>{/* your own logic here */}</title>
      </Head>
    );
  }
});

export default {
  roots: {
    archiveTitles: ArchiveTitles,
  },
};
```

@codemonkeynorth feel free to reopen if you think this should be addressed in a different way and want to keep the discussion.
